# Generated by Django 3.2.8 on 2022-11-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-timestamp',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
