# Generated by Django 4.1.3 on 2022-11-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='online',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
