# Generated by Django 4.1.3 on 2022-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_useractivity_last_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='last_logout_time',
            field=models.DateTimeField(null=True),
        ),
    ]
