# Generated by Django 4.1.3 on 2022-11-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_useractivity_last_logout_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='last_logout_time',
        ),
    ]
